// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKG31zuHwjGCM-nzNM8UduY0dapucsmSA',
    appId: '1:393679648995:web:ff33d6aed91a48ed7cedd6',
    messagingSenderId: '393679648995',
    projectId: 'to-dufler',
    authDomain: 'to-dufler.firebaseapp.com',
    storageBucket: 'to-dufler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBCr6aQY7_GYfHwGhnB3t1tt7cC2bAYU',
    appId: '1:393679648995:android:27066c42424ff6ce7cedd6',
    messagingSenderId: '393679648995',
    projectId: 'to-dufler',
    storageBucket: 'to-dufler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgSr0lAEZirWMrh-W14pM6Cx2wYVsvFec',
    appId: '1:393679648995:ios:dd43a9f73ac12b167cedd6',
    messagingSenderId: '393679648995',
    projectId: 'to-dufler',
    storageBucket: 'to-dufler.firebasestorage.app',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgSr0lAEZirWMrh-W14pM6Cx2wYVsvFec',
    appId: '1:393679648995:ios:dd43a9f73ac12b167cedd6',
    messagingSenderId: '393679648995',
    projectId: 'to-dufler',
    storageBucket: 'to-dufler.firebasestorage.app',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKG31zuHwjGCM-nzNM8UduY0dapucsmSA',
    appId: '1:393679648995:web:f153f1e92a91a5ce7cedd6',
    messagingSenderId: '393679648995',
    projectId: 'to-dufler',
    authDomain: 'to-dufler.firebaseapp.com',
    storageBucket: 'to-dufler.firebasestorage.app',
  );

}